name: Testing capital.com

on: workflow_dispatch
  
jobs:
  tests:
  
    name: I. Bild enviroment
    runs-on: macos-latest
    steps:
    - name: 1. Get repository code
      uses: actions/checkout@v3
             
    - name: 2. Instal JDK
      if: always()
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
       
    - name: Tests Run
      if: always()
      run:
        ls -la
        mvn -f /Users/runner/work/Autotesting/Autotesting/RegistrationOfCapital/pom.xml clean test -Dtest="CheckRegBtnTicSharesTest"
        
    - name: 8. Upload artifact "allure-results"
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: allure-results
          path: allure-results/
          retention-days: 10







  generate_report:
    name: Generate & Deploy Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]
    steps:
    
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Allure Report about testing
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: target/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        
    - name: 5. Archive code coverage results
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: allure_report
          path: allure_report/
  
  
  
  
  
