name: Testing capital.com

on: workflow_dispatch
  
jobs:
  tests:
  
    name: I. Bild enviroment and testing
    runs-on: macos-latest
    steps:
    - name: 1. Get repository code
      uses: actions/checkout@v3
             
    - name: 2. Instal JDK
      if: always()
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
       
    - name: 3. Tests Run
      if: always()
      run: mvn -f /Users/runner/work/Autotesting/Autotesting/RegistrationOfCapital/pom.xml clean test -Dtest="CheckRegBtnTicSharesTest"
       
    - name: 4. Upload artifact "allure-results"
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: RegistrationOfCapital/target/allure-results
        retention-days: 10
    
    - name: 5. Show me folder
      run:
        ls -la;
        cd RegistrationOfCapital/target/allure-results;
        ls -la;
      


  generate_report:
    name: II. Generate & Deploy Allure report
    runs-on: ubuntu-latest
    if: always()
    needs: [ tests ]
    steps:
      - name: 1. Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: 2. Download Artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          name: allure-results
          path: RegistrationOfCapital/target/allure-results

      - name: 3. Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: RegistrationOfCapital/target/allure-results
          allure_report: RegistrationOfCapital/target/allure-report
          allure_history: allure-history
          gh_pages: gh-pages
          ref: gh-pages
          path: gh-pages
          keep_reports: 15

      - name: 4. Deploy allure_report to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: allure-history

      - name: 5. Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure_report
          path: allure_report/ 
  
  
  
